### ISSUE TITLE
Parse error on TransactionResponse

### ISSUE THREAD

**Issue by apegineer** [y-pakorn/flutter_web3#3]
I am trying to use Contract.send() and this is always the error I got.
```
Uncaught (in promise) Error: Expected a value of type 'FutureOr<TransactionResponse>?', but got one of type 'NativeJavaScriptObject'
    at Object.throw_ [as throw] (errors.dart:236)
    at Object.castError (errors.dart:84)
    at Object.cast [as as] (operations.dart:442)
    at dart.NullableType.new.as (types.dart:417)
    at js_util.dart:183
```

The code is as follow:
```
final abi = ['function mintTo(address _to) public payable'];
final contract = Contract(
        contractAddr, Interface(abi), web3provider.getSigner());
final txConfig = TransactionOverride(
      gasLimit: BigInt.from(1000000),
      value: BigInt.from(1000000),
      gasPrice: BigInt.from(1000000),
      nonce: 0,
    );
final response = await contract.send(
      'mintTo',
      ['<some_address>'],
      txConfig,
    );
```

Any idea how to fix this?

**Comment by y-pakorn** [comment]
Please update to lastest version, this is already fixed on v2.0.3.

Thank you!

**Comment by communitycolors** [comment]
This issue still seems to happen when calling

`    final tx = await contract.send(
        'tokenURI',
        [478392],
    );
`

`
Uncaught (in promise) Error: Expected a value of type 'FutureOr<_TransactionResponseImpl>?', but got one of type 'String'
    at Object.throw_ [as throw] (errors.dart:251)
    at Object.castError (errors.dart:84)
    at Object.cast [as as] (operations.dart:452)
    at dart.NullableType.new.as (types.dart:367)
    at js_util.dart:229
`
